////////////////////////////////////////////////////////////////////////
// Class:       SPECalibration
// Module Type: analyzer
// File:        SPECalibration_module.cc
//
// Analyzer to read optical waveforms
//
// Authors: Adapted by acastill from original implementation by A. Szelc, H. Parkinson, and A. Hamer.
////////////////////////////////////////////////////////////////////////

#include <algorithm>
#include <vector>
#include <cmath>
#include <memory>
#include <string>
#include <iostream>

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art_root_io/TFileService.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "canvas/Utilities/Exception.h"
#include "art/Framework/Services/Registry/ServiceHandle.h"
#include "larcore/Geometry/Geometry.h"
#include "larcore/Geometry/WireReadout.h"

#include "lardata/DetectorInfoServices/DetectorClocksService.h"
#include "lardata/DetectorInfoServices/DetectorClocksServiceStandard.h"
#include "lardata/DetectorInfoServices/DetectorPropertiesService.h"
#include "lardata/DetectorInfoServices/LArPropertiesService.h"
#include "lardataobj/RawData/OpDetWaveform.h"
#include "sbndcode/Utilities/SignalShapingServiceSBND.h"
#include "lardataobj/Simulation/sim.h"
#include "lardataobj/Simulation/SimChannel.h"
#include "lardataobj/Simulation/SimPhotons.h"

#include "TH1D.h"
#include "TFile.h"
#include "TTree.h"
#include "TMarker.h"
#include "lardataobj/RawData/OpDetWaveform.h"
#include "lardata/Utilities/LArFFT.h"
#include "TFile.h"

#include <cmath>
#include "TCanvas.h"
#include "TH1.h"
#include "TF1.h"
#include "TComplex.h"

#include <iostream>
#include <vector>
#include <cmath>
#include <string>
#include <numeric>
#include "TVector2.h"
#include "TH2D.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TTree.h"
#include "TFile.h"
#include "TGraph.h"

#include "sbndcode/OpDetSim/sbndPDMapAlg.hh"

namespace PDSCali{

  class SPECalibration;

  class SPECalibration : public art::EDAnalyzer {
    public:
    explicit SPECalibration(fhicl::ParameterSet const & p);
    // The destructor generated by the compiler is fine for classes
    // without bare pointers or other resource use.

    // Plugins should not be copied or assigned.
    SPECalibration(SPECalibration const &) = delete;
    SPECalibration(SPECalibration &&) = delete;
    SPECalibration & operator = (SPECalibration const &) = delete;
    SPECalibration & operator = (SPECalibration &&) = delete;

    // Required functions.
    void analyze(art::Event const & e) override;

    //Selected optional functions
    void beginJob() override;
    void endJob() override;

    opdet::sbndPDMapAlg pdMap; //map for photon detector types  USE THIS TO SELECT ONLY PMTs!!

    private:

    std::vector<std::string> fOpChannelsType;
    std::vector<int> fOpChannelList;
    int fMaxPulseAmp;
    int fMaxNPeaks; // Max number of peaks to be found in a single waveform

    // Declare member data here.
    std::string fInputModuleName;
    std::stringstream histname;
    std::string opdetType;
    std::string opdetElectronics;
    double fNstdev; //number of noise stdevs to set the threshold to
    int fSpe_region_start; //number of bins after which SPE search starts
    std::vector<TH1D *> amp;
    art::ServiceHandle<art::TFileService> tfs;
  };

  SPECalibration::SPECalibration(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p) { // ,
    // More initializers here.

    fInputModuleName = p.get< std::string >("InputModule" );
    fNstdev = p.get < double >("nstdev");
    fSpe_region_start = p.get < int >("spe_region_start");
    fOpChannelsType = p.get < std::vector<std::string> >("OpChannelsType");
    fMaxPulseAmp = p.get < double >("MaxPulseAmp");
    fMaxNPeaks = p.get < int >("MaxNPeaks");

    geo::WireReadoutGeom const& fWireReadout = art::ServiceHandle<geo::WireReadout>()->Get();

    for(unsigned int opch=0; opch<fWireReadout.NOpChannels(); opch++){
      std::string _pd_type = pdMap.pdType(opch);
      if(std::find(fOpChannelsType.begin(), fOpChannelsType.end(), _pd_type) == fOpChannelsType.end()) continue; //skip if not in the list of types
      else fOpChannelList.push_back(opch); //if in the list, save the channel number for later use
    }

    for(unsigned int ch=0;ch<fOpChannelList.size();ch++)
    {
      amp.push_back(tfs->make< TH1D >(Form("amp_opchannel_%i", fOpChannelList[ch]), Form("Amplitude of SPEs, channel %i;Amplitude[ADC];Count", fOpChannelList[ch]), 200, 0, 200)); // create histogram for amplitude
    }
  }

  void SPECalibration::beginJob()
  {

  }


  void SPECalibration::analyze(art::Event const & e)
  {

    art::Handle<std::vector<raw::OpDetWaveform>> waveHandle;
    e.getByLabel(fInputModuleName, waveHandle);

    if(!waveHandle.isValid()) {
      std::cout << Form(
        "Did not find any G4 photons from producer %s",
        "largeant"
      ) << std::endl;

      return;
    }

    double pulse_peak;
    double pulse_t_start;
    double pulse_t_end;
    double pulse_t_peak;

    std::vector<double> pulse_t_peak_v;

    int total_nspe = 0;

    int success = 0;
    int failed = 0;

    std::cout
        << "Number of waveforms: "
        << waveHandle->size()
        << std::endl;

    for(auto const& wvf : (*waveHandle))
    {
      int wvf_ch = wvf.ChannelNumber();

      opdetType        = pdMap.pdType(wvf_ch);
      opdetElectronics = pdMap.electronicsType(wvf_ch);
      
      //--------------------------------------------------
      // BASELINE ESTIMATION
      //--------------------------------------------------

      const int wvf_nbins = wvf.size();
      std::vector<int> sortedWVF( wvf.begin(), wvf.end());
      std::sort( sortedWVF.begin(), sortedWVF.end());

      double baseline;
      int n = sortedWVF.size();
      if(n % 2 == 0){
        baseline = 0.5 * ( sortedWVF[n/2 - 1] + sortedWVF[n/2] );
      }
      else{
        baseline = sortedWVF[n/2];
      }

      //--------------------------------------------------
      // BASELINE SUBTRACTION + POLARITY FLIP
      //--------------------------------------------------

      std::vector<double> wvfm(wvf_nbins, 0);

      for(int i=0;i<wvf_nbins;i++){
        wvfm[i] = baseline - (double)wvf[i];
      }

      //--------------------------------------------------
      // REJECT LARGE PULSES
      //--------------------------------------------------

      double max_value = *std::max_element( wvfm.begin(), wvfm.end());

      if(max_value > fMaxPulseAmp)
        continue;

      //--------------------------------------------------
      // NOISE ESTIMATION USING FULL WAVEFORM
      //--------------------------------------------------

      double totalvar = 0;

      for(int i=0;i<wvf_nbins;i++){
        double val = wvfm[i];
        totalvar +=val*val;
      }

      double stdev = sqrt(totalvar / wvf_nbins);
      double thresh = stdev * fNstdev;

      //--------------------------------------------------
      // PEAK FINDER
      //--------------------------------------------------

      bool fire = false;

      int counter = fSpe_region_start;

      int peak_count = 0;

      pulse_t_peak_v.clear();

      pulse_peak    = 0;
      pulse_t_start = 0;
      pulse_t_end   = 0;
      pulse_t_peak  = 0;

      for(unsigned int i=fSpe_region_start;i<wvfm.size();i++)
      {
        double adc =
            wvfm[counter];

        if(!fire && adc > thresh){
          fire = true;
          pulse_t_start = counter-1 > 0?counter-1:counter;
        }

        else if(fire && adc < thresh){
          fire = false;
          pulse_t_end = counter <(int)wvfm.size()?counter:counter-1;

          if(pulse_t_end-pulse_t_start>2){
            pulse_t_peak_v.push_back(pulse_t_peak);
            peak_count++;
          }

          pulse_peak    = 0;
          pulse_t_start = 0;
          pulse_t_end   = 0;
          pulse_t_peak  = 0;
        }

        else if(fire){
          if(adc > pulse_peak){
            pulse_peak = adc;
            pulse_t_peak = counter;
          }
        }
        counter++;

        if(peak_count == fMaxNPeaks){
          failed++;
          continue;
        }
      }

      //--------------------------------------------------
      // HANDLE OPEN PULSE
      //--------------------------------------------------

      if(fire){
        fire = false;
        pulse_t_end = counter-1;
      }

      //--------------------------------------------------
      // AMPLITUDES
      //--------------------------------------------------

      int nspe = pulse_t_peak_v.size();

      if(nspe == 0){
        failed++;
        continue;
      }

      for(int i=0; i<nspe; i++){
        int peakbin = pulse_t_peak_v[i];
        double ampsum = 0;
        int ampnumBins = 0;
        for(int j=peakbin-20; j<=peakbin+20; j++)
        {
          if(j>=0 && j<(int)wvfm.size())
          {
            ampsum += wvfm[j];
            ampnumBins++;
          }
        }

        double localBaseline = ampsum / ampnumBins;
        double peakheight = wvfm[peakbin]-localBaseline;

        int idx = std::find(fOpChannelList.begin(), fOpChannelList.end(), wvf_ch) - fOpChannelList.begin();
        amp[idx]->Fill(
            peakheight
        );
      }

      success++;
      total_nspe +=peak_count;
    }

    //--------------------------------------------------
    // FINAL PRINT
    //--------------------------------------------------

    std::cout
        << "Analysis complete\n"
        << "Successful waveforms: "
        << success
        << "\nFailed waveforms: "
        << failed
        << "\nTotal SPEs: "
        << total_nspe
        << std::endl;
  }

  void SPECalibration::endJob()
  {

  }

  DEFINE_ART_MODULE(PDSCali::SPECalibration)

  }