#!/bin/bash

root -l -b -q 'ConfusionMatrixChi2.C++(true, false, false, true, -1, -1)'
root -l -b -q 'ConfusionMatrixChi2.C(true, false, false, false, -1, -1)'
root -l -b -q 'ConfusionMatrixChi2.C(false, true, false, true, -1, -1)'
root -l -b -q 'ConfusionMatrixChi2.C(false, true, false, false, -1, -1)'
root -l -b -q 'ConfusionMatrixChi2.C(false, false, true, true, -1, -1)'
root -l -b -q 'ConfusionMatrixChi2.C(false, false, true, false, -1, -1)'
root -l -b -q 'ConfusionMatrixChi2.C(true, false, false, true, .5, .5)'
root -l -b -q 'ConfusionMatrixChi2.C(true, false, false, false, .5, .5)'
root -l -b -q 'ConfusionMatrixChi2.C(false, true, false, true, .5, .5)'
root -l -b -q 'ConfusionMatrixChi2.C(false, true, false, false, .5, .5)'
root -l -b -q 'ConfusionMatrixChi2.C(false, false, true, true, .5, .5)'
root -l -b -q 'ConfusionMatrixChi2.C(false, false, true, false, .5, .5)'
root -l -b -q 'ConfusionMatrixChi2.C(true, false, false, true, .8, .8)'
root -l -b -q 'ConfusionMatrixChi2.C(true, false, false, false, .8, .8)'
root -l -b -q 'ConfusionMatrixChi2.C(false, true, false, true, .8, .8)'
root -l -b -q 'ConfusionMatrixChi2.C(false, true, false, false, .8, .8)'
root -l -b -q 'ConfusionMatrixChi2.C(false, false, true, true, .8, .8)'
root -l -b -q 'ConfusionMatrixChi2.C(false, false, true, false, .8, .8)'
