////////////////////////////////////////////////////////////////////////
// Class:       SBNDXARAPUCADecoder
// Plugin Type: producer
// File:        SBNDXARAPUCADecoder_module.cc
// Author:      Alicia Vázquez-Ramos (aliciavr@ugr.es)
////////////////////////////////////////////////////////////////////////

/**
 * @file SBNDXARAPUCADecoder_module.cc
 * @brief Defines and implements the SBNDXARAPUCADecoder class which inherits from an art::EDProducer
 * as the decoder for V1740B digitizers, intended for the X-ARAPUCAs.
 * @details The current version of the SBND X-ARAPUCAs decoder implements the updates shown in 
 * the SBN Document 43891-v1 in the SBN Document Database.
 * @note A Python version of the binary decoding is available for testing purposes. You can find 
 * it [here: V1740 binary decoder](https://github.com/aliciavr/V1740_binary_decoder).
 * @version 5.0
 */

#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "artdaq-core/Data/Fragment.hh"
#include "artdaq-core/Data/ContainerFragment.hh"
#include "artdaq-core/Data/RawEvent.hh"

#include "sbndaq-artdaq-core/Overlays/FragmentType.hh"
#include "sbndaq-artdaq-core/Overlays/SBND/CAENV1740Fragment.hh"

#include "sbndcode/Timing/SBNDRawTimingObj.h"
#include "sbnobj/SBND/Timing/DAQTimestamp.hh"

#include "sbnobj/SBND/Timing/FrameShiftInfo.hh"

#include "lardataobj/RawData/OpDetWaveform.h"

#include "art_root_io/TFileService.h"
#include "TH1I.h"

#include <memory>
#include <algorithm>


/**
 * @namespace sbndaq
 * @brief Contains classes and functions for inside the sbndaq system.
 */
namespace sbndaq {
  class SBNDXARAPUCADecoder;
}


/**
 * @class SBNDXARAPUCADecoder
 * @brief A class providing the V1740B digitizer decoder. It inherits from art::EDProducer and 
 * creates a vector of raw::OpDetWaveform objects as a product of the decoding.
 */
class sbndaq::SBNDXARAPUCADecoder : public art::EDProducer {
public:
  explicit SBNDXARAPUCADecoder(fhicl::ParameterSet const& p);

  SBNDXARAPUCADecoder(SBNDXARAPUCADecoder const&) = delete;
  SBNDXARAPUCADecoder(SBNDXARAPUCADecoder&&) = delete;
  SBNDXARAPUCADecoder& operator=(SBNDXARAPUCADecoder const&) = delete;
  SBNDXARAPUCADecoder& operator=(SBNDXARAPUCADecoder&&) = delete;

  // Main class method.
  void produce(art::Event& e) override;

private:
  constexpr static uint64_t NANOSEC_IN_SEC = 1'000'000'000; /**< Number of nanoseconds in one second. */
  constexpr static uint64_t MICROSEC_IN_NANOSEC = 1'000; /**< Number of nanoseconds in one microsecond. */
  constexpr static double   NANOSEC_TO_MICROSEC = 1E-3; /**< Conversion factor from nanoseconds to microseconds. */

  constexpr static uint32_t BITS_PER_WORD = 32; /**< Number of bits per word in the V1740B digitizer (32-bit word). */
  constexpr static uint32_t BITS_PER_SAMPLE = 12; /**< Bit precision of the V1740B digitizer (12-bit resolution per sample). */
  constexpr static uint32_t NUM_CHANNELS_PER_GROUP = 8; /**< Number of channels in each channel group of the V1740B digitizers. */
  constexpr static uint32_t NUM_GROUPS = 8; /**< Number of channel groups for the V1740B digitizers. */
  constexpr static uint32_t NUM_SAMPLES_PER_ROUND = 24; /**< Number of samples to be read in each channel group round. */
  constexpr static uint32_t NUM_CONSECUTIVE_SAMPLES = 3; /**< Number of consecutive samples for the same channel when decoding waveforms. */
  constexpr static uint16_t NANOSEC_PER_TICK = 8; /**< Number of nanoseconds per Trigger Time Tag (TTT) tick. */

  constexpr static uint16_t FRAMESHIFT_TIMING = 0; /**< Timing reference frame: FrameShift timestamp. */
  constexpr static uint16_t CAEN_ONLY_TIMING = 1; /**< Timing reference frame: CAEN-only. */

  constexpr static uint16_t TTT_DEFAULT = 0; /**< Default integer value for the nominal TTT. */

  unsigned int fevent_counter; /**< Event counter. */

  unsigned int fnum_caen_boards; /**< Maximum number of CAEN boards to be considered. */
  unsigned int ffragment_id_offset; /**< Offset value to get the slot of every CAEN board. */
  std::vector<unsigned int> fboard_id_list; /**< Possible CAEN board identifiers based on the slot they are installed. */

  std::string fcaen_module_label; /**< Label identifying the module where the CAEN fragments come from. */
  std::vector<std::string> fcaen_fragment_names; /**< Fragments accepted by this decoder. */

  std::string fwaveforms_instance_name; /**< Name assigned to the product instance containing the waveforms for each channel and board generated by this art::EDProducer. */
  std::string ftiming_ref_instance_name; /**< Name assigned to the product instance containing the timing reference information for each event generated by this art::EDProducer. */

  bool fframeshift_mode; /**< FrameShift mode: 0 use timing priority, 1 use FrameShift timestamp as reference. */
  uint16_t factive_timing_frame; /**< Active timing frame while processing each event. */
  unsigned int fns_per_sample; /**< Number of nanoseconds per sample. */

  std::string fframeshift_product_name; /**< Label identifying the module containing the FrameShift module products. */

  art::ServiceHandle<art::TFileService> tfs; /**<  ServiceHandle object to store the histograms in the decoder_hist.root output file. */
  int fstore_debug_waveforms; /**< Number of waveforms to store in the ServiceHandle object for debugging purposes (0: none, -1: all, n: first n waveforms each event). */

  bool fcombine_ext_frag; /**< If `true` combines extended fragments into a single raw::OpDetWaveform object. */
  int32_t fallowed_jittering; /**< Allowed jittering (in ns) between fragments to be combined. */

  bool fdebug_frameshift_handle; /**< If `true` FrameShift information is printed. */
  bool fdebug_fragments_handle; /**< If `true` V1740B CAEN fragments art::Handle information is printed. */
  bool fdebug_timing; /**< If `true` timing data is printed. */
  bool fdebug_buffer; /**< If `true` the buffer status is printed. */
  bool fdebug_waveforms; /**< If `true` waveforms decoding data is printed. */
  bool fdebug_extended_fragments; /**< If `true` extended fragments information is printed. */
  bool fdebug_jittering; /**< If `true` trigger jittering information is printed. */
  bool fverbose; /**< If `true` it increases verbosity of console output for detailed processing steps. */

  // Main processing method.
  void decode_fragment(uint64_t timestamp, uint64_t& first_frag_timestamp, size_t& first_frag_idx, int32_t& first_TTT, int32_t& prev_TTT, std::vector<size_t> & fragment_indices, const artdaq::Fragment& fragment, std::vector <raw::OpDetWaveform>& prod_wvfms, std::vector<std::vector<uint16_t>>& wvfms, bool last_one, size_t& appended_samples);
  
  // Timing.
  void shift_time(uint64_t TTT_ticks, int64_t TTT_end_ns, uint64_t frag_timestamp, uint64_t timestamp, uint32_t num_samples_per_wvfm, double& ini_wvfm_timestamp, double& end_wvfm_timestamp, size_t& appended_samples);
  std::unique_ptr<raw::TimingReferenceInfo> get_frameshift_timestamp(art::Event& e, uint64_t& timestamp);

  // Waveforms decoding.
  void decode_waveforms(const artdaq::Fragment& fragment, std::vector<std::vector<uint16_t>>& wvfms, size_t header_size, uint32_t num_channels, uint32_t num_samples_per_wvfm, uint32_t num_words_per_wvfms, uint32_t num_samples_per_group);
  uint16_t get_sample(uint64_t buffer, uint32_t msb, uint32_t lsb);
  uint32_t read_word(const uint32_t* & data_ptr);
  unsigned int get_channel_id(unsigned int board, unsigned int board_channel);

  // Combines decoded waveforms.
  void append_waveforms(std::vector<std::vector<uint16_t>>& wvfms, const std::vector<std::vector<uint16_t>>& fragment_wvfms, uint32_t num_channels);

  // Dumps and saves waveforms.
  void dump_waveforms(std::vector <raw::OpDetWaveform> & prod_wvfms, std::vector<std::vector<uint16_t>>& wvfms, size_t first_frag_idx, size_t board_index, uint32_t num_channels, double ini_wvfm_timestamp, double end_wvfm_timestamp);
  void save_prod_wvfm(size_t board_idx, size_t ch, double ini_wvfm_timestamp, const std::vector <std::vector <uint16_t> > & wvfms, std::vector <raw::OpDetWaveform> & prod_wvfms);
  void save_debug_wvfm(size_t board_idx, size_t fragment_idx, int ch, double ini_wvfm_timestamp, double end_wvfm_timestamp, const std::vector <std::vector <uint16_t> > & wvfms);
  
  // Auxiliary methods.
  int64_t signed_difference_UTC_timestamp(uint64_t t1, uint64_t t2);
  uint64_t abs_difference(uint64_t t1, uint64_t t2);
  std::string print_timestamp(uint64_t timestamp);

};

/**
 * @brief Constructor of the class SBNDXARAPUCADecoder. Given a fhicl::ParameterSet object it gets the configuration needed by this 
 * art::EDProducer from the FHiCL file.
 * @param[in] p A set of parameters containing configuration values for the decoder from the FHiCL file.
 * @details This constructor accesses the parameters in the FHiCL configuration file and set the configuration to be run for 
 * this module. It sets settings for CAEN fragments, board information, timing, debug and verbosity options, and creates
 * instances of the products associated with this module: a vector of raw::OpDetWaveform objects and a raw::TimingReferenceInfo object.
 */
sbndaq::SBNDXARAPUCADecoder::SBNDXARAPUCADecoder(fhicl::ParameterSet const& p)
: EDProducer{p}
{
  // Sets the event counter to zero.
  fevent_counter = 0;
  
  // Gets the CAEN fragments information.
  fcaen_module_label = p.get<std::string> ("caen_module_label", "daq");
  fcaen_fragment_names = p.get<std::vector <std::string> > ("caen_fragment_names", {"CAENV1740", "ContainerCAENV1740"});

  // Gets the CAEN boards information.
  ffragment_id_offset = p.get<unsigned int> ("fragment_id_offset", 41216);
  fboard_id_list = p.get<std::vector <unsigned int> > ("board_id_list", {7, 13, 16, 19});
  fnum_caen_boards = p.get<unsigned int> ("num_caen_boards", 4);
  
  // Gets the name of the instance created by this module.
  fwaveforms_instance_name = p.get<std::string> ("waveforms_instance_name", "XARAPUCAChannels");
  ftiming_ref_instance_name = p.get<std::string> ("timing_ref_instance_name", "");

  // Gets timing configuration.
  factive_timing_frame = CAEN_ONLY_TIMING;
  fns_per_sample = p.get<unsigned int> ("ns_per_sample", 16);

  // FrameShift access configuration.
  fframeshift_product_name = p.get<std::string>("frameshift_product_name", "frameshift");
  
  // Gets the number of waveforms to store in the debug output file.
  fstore_debug_waveforms = p.get<int> ("store_debug_waveforms", 0);

  // Gets the combination of extended fragments option.
  fcombine_ext_frag = p.get<bool> ("combine_ext_frag", true);
  fallowed_jittering = p.get<int32_t> ("allowed_jittering", 64);

  // Gets the debug and verbose options.
  fdebug_frameshift_handle = p.get<bool> ("debug_frameshift_handle", false);
  fdebug_fragments_handle = p.get<bool> ("debug_fragments_handle", false);
  fdebug_timing = p.get<bool> ("debug_timing", false);
  fdebug_waveforms = p.get<bool> ("debug_waveforms", false);
  fdebug_extended_fragments = p.get<bool> ("debug_extended_fragments", false);
  fdebug_jittering = p.get<bool> ("debug_jittering", false);
  fdebug_buffer = p.get<bool> ("debug_buffer", false);
  fverbose = p.get<bool> ("verbose", false);

  // Creates the instance product of this module.
  produces <std::vector <raw::OpDetWaveform> > (fwaveforms_instance_name);
  produces <raw::TimingReferenceInfo> (ftiming_ref_instance_name);
}

 /** 
  * @brief Main function of the art::EDProducer: the produce function analyzes every event producing waveforms after the decoding.
  * @param[in] e The event to be processed.
  * @details It is the main function of the art::EDProducer module: it processes each event, searches for CAEN V1740 fragments, decodes 
  * them and creates the output products.
  * 1. It gets the raw timestamp from the artdaq::RawEventHeader product.
  * 2. It tries to get a valid timing reference from the selected time frame (FRAMESHIFT or CAEN-only). If the selected 
  * timing frame is not found, it tries to get the next one in the priority list.
  * 3. It searches for CAEN V1740 fragments in the event, decodes them and creates the output products: a vector of raw::OpDetWaveform.
  * 4. It dumps the products in the event.
  */
void sbndaq::SBNDXARAPUCADecoder::produce(art::Event& e) {
  if (fverbose) std::cout << "\n > SBNDXARAPUCADecoder::produce: entering the produce function." << std::endl;

  // Advances the event counter.
  fevent_counter++;

  // Initializes the output instance products.
  auto prod_wvfms = std::make_unique <std::vector <raw::OpDetWaveform> > ();
  // CAEN-only timing frame as default.
  auto prod_event_timing_ref_info = std::make_unique<raw::TimingReferenceInfo>(CAEN_ONLY_TIMING, 0); // CAEN-only timing frame as default.

  if (fverbose) std::cout << "\n > SBNDXARAPUCADecoder::produce: products initialized." << std::endl;

  uint64_t timestamp = 0;           
  
  // ============= FRAMESHIFT TIMING ============ //
  if (auto fs_timing_ref_info = get_frameshift_timestamp(e, timestamp)) {
    *prod_event_timing_ref_info = *fs_timing_ref_info;
    factive_timing_frame = FRAMESHIFT_TIMING;
    if (fverbose | fdebug_frameshift_handle) {
      std::cout << "\n > SBNDXARAPUCADecoder::produce: FRAMESHIFT reference, " << print_timestamp(timestamp) << ", found. Using FRAMESHIFT timing frame as reference." << std::endl;
      std::cout << "\t FRAMESHIFT reference details: timing type: " << prod_event_timing_ref_info->timingType << ", timing channel: " << prod_event_timing_ref_info->timingChannel << "." << std::endl;
    }
  } else {
    if (fverbose | fdebug_frameshift_handle) std::cout << "\n > SBNDXARAPUCADecoder::produce: FrameShift reference not found. Using CAEN-only timing frame as reference." << std::endl;
  }
  // ============================================== //


  // Flag to track if valid CAEN fragments are found.
  bool found_caen = false;

  std::vector<size_t> fragment_indices(fnum_caen_boards, -1);
  std::vector<std::vector <uint16_t>> wvfms;
  if (fdebug_extended_fragments) {
    std::cout << " Waveforms size: " << wvfms.size() << std::endl;
  }
  
  size_t appended_samples = 0;
  size_t first_frag_idx = 0;
  int32_t first_TTT = TTT_DEFAULT;
  int32_t prev_TTT = 0;
  uint64_t first_frag_timestamp = TTT_DEFAULT;
  bool last_one = false;

  if (fverbose | fdebug_fragments_handle) std::cout << "\n > SBNDXARAPUCADecoder::produce: searching for V1740 fragments..." << std::endl;
  
  for (const std::string &caen_name: fcaen_fragment_names) {
    art::Handle <std::vector <artdaq::Fragment> > fragment_handle;
    e.getByLabel(fcaen_module_label, caen_name, fragment_handle);
    
    // The art::Handle object is not valid.
    if (!fragment_handle.isValid()) { 
      if (fdebug_fragments_handle) std::cout << "\tHandle not valid for " << caen_name << "." << std::endl;
    
    // The art::Handle object is empty.
    } else if (fragment_handle->size() == 0) { 
      if (fdebug_fragments_handle) std::cout << "\tHandle with size " << fragment_handle->size() << " for " << caen_name << "."<< std::endl;
    
    // The art::Handle object is valid and not empty.
    } else { 
      found_caen |= true;
      size_t frag_handle_size = fragment_handle->size();

      if (fdebug_fragments_handle) std::cout << "\tHandle valid for " << caen_name << " (" << frag_handle_size << " objects)." << std::endl;
    
      // It is a group of containers containing a group of CAEN V1740 fragments.
      if (fragment_handle->front().type() == artdaq::Fragment::ContainerFragmentType){
        
        // For every container,
        for (size_t c = 0; c < frag_handle_size; c++) {
          auto container = fragment_handle->at(c);
          artdaq::ContainerFragment container_fragment(container);
          
          // it searches for all CAEN V1740 fragments inside the container if it contains CAEN V1740 fragments.
          if (container_fragment.fragment_type() == sbndaq::detail::FragmentType::CAENV1740) {
            size_t num_caen_fragments = container_fragment.block_count(); 
            if (fdebug_fragments_handle) std::cout << "\t\tContainerCAENV1740 "<< c << " - CAENV1740 fragments found: " << num_caen_fragments << "." << std::endl;
            
            for (size_t f = 0; f < num_caen_fragments; f++) {
              const artdaq::Fragment fragment = *container_fragment[f].get();
              last_one = f == (num_caen_fragments - 1);
              decode_fragment(timestamp, first_frag_timestamp, first_frag_idx, first_TTT, prev_TTT, fragment_indices, fragment, *prod_wvfms, wvfms, last_one, appended_samples);
            } // End CAEN V1740 fragments loop.
          }
        } // End Container fragments loop.
    
      // It is a group of CAEN V1740 fragments.
      } else if (fragment_handle->front().type() == sbndaq::detail::FragmentType::CAENV1740) {
        if (fdebug_fragments_handle) std::cout << "\t\tCAENV1740 fragments found: " << frag_handle_size << "." << std::endl;
        
        // It searches for all CAEN V1740 fragments.
        for (size_t f = 0; f < frag_handle_size; f++) {
          const artdaq::Fragment fragment = fragment_handle->at(f);
          last_one = f == (frag_handle_size - 1);
          decode_fragment(timestamp, first_frag_timestamp, first_frag_idx, first_TTT, prev_TTT, fragment_indices, fragment, *prod_wvfms, wvfms, last_one, appended_samples);
        } // End CAEN V1740 fragments loop.
      }
    } // End extracting CAEN V1740 fragments.
    fragment_handle.removeProduct();
  } // End CAEN fragment names loop.

  // Dumps the products of this art::EDProducer.
  e.put(std::move(prod_wvfms), fwaveforms_instance_name);
  e.put(std::move(prod_event_timing_ref_info), ftiming_ref_instance_name);

  if (fverbose) {
    if (!found_caen) {
      std::cout << "\n > SBNDXARAPUCADecoder::produce: no CAEN V1740 fragments of any type found, pushed empty waveforms." << std::endl;
    } else {
      std::cout << "\n > SBNDXARAPUCADecoder::produce: waveforms for all valid fragments dumped." << std::endl;
    }
    std::cout << "\n > SBNDXARAPUCADecoder::produce: end of the producer function.\n\n" << std::endl;
  } 
}

// ===============  Main fragment processing method ===============  //

/**
 * @brief Decodes a CAEN V1740 fragment, extracts the waveforms and combines them into the output product.
 * @param[in] timestamp The valid timestamp used as reference for the event.
 * @param[in,out] first_frag_timestamp The nominal timestamp calculated for the fragment being processed.
 * @param[in, out] first_frag_idx The first index of the fragments being combined.
 * @param[in,out] first_TTT The nominal Trigger Time Tag (TTT) calculated for the fragment being processed.
 * @param[in,out] fragment_indices A vector containing the indices of the fragments already processed for each board.
 * @param[in] fragment The artdaq::Fragment object to be processed.
 * @param[in,out] prod_wvfms The vector of raw::OpDetWaveform objects to be filled with the decoded waveforms.
 * @param[in,out] wvfms A 2D vector containing the waveforms for all channels and boards decoded so far.
 * @param[in] last_one A boolean flag indicating if the fragment being processed is the last one in the event.

 * @details This method decodes a CAEN V1740 fragment, extracts the waveforms for each channel, shifts them in time according to the
 * timing reference and combines them into the output product.
 *    1. It checks if the fragment ID corresponds to a valid board.
 *    2. It accesses the metadata and header of the fragment to get information about the number of channels, samples, words, etc.
 *    3. It calculates the number of samples per waveform and checks if it is a nominal or extended fragment.
 *    4. It decodes the waveforms for each channel in the fragment.
 *    5. It shifts the waveforms in time according to the timing reference.
 *    6. It combines the decoded waveforms into the output product.
 *    7. It dumps the waveforms if required.
 * 
 * @pre The art::Event object containing the fragment has been processed to get a valid timing reference.
 * @post The vector of raw::OpDetWaveform objects is filled with the decoded waveforms from the fragment.
 * @see shift_time
 * @see decode_waveforms
 * @see append_waveforms
 * @see dump_waveforms
 */

void sbndaq::SBNDXARAPUCADecoder::decode_fragment(uint64_t timestamp, uint64_t& first_frag_timestamp, size_t& first_frag_idx, int32_t& first_TTT, int32_t& prev_TTT, std::vector<size_t> & fragment_indices, const artdaq::Fragment& fragment, std::vector <raw::OpDetWaveform>& prod_wvfms,  std::vector<std::vector<uint16_t>>& wvfms, bool last_one, size_t& appended_samples) {
  auto fragment_id = fragment.fragmentID() - ffragment_id_offset;
  auto it = std::find(fboard_id_list.begin(), fboard_id_list.end(), fragment_id);
  size_t board_idx;
  bool valid_fragment = false;

  if (it != fboard_id_list.end()) {
    board_idx = it - fboard_id_list.begin();
    if (board_idx >= fnum_caen_boards) {
      if (fverbose) std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: fragment ID " << fragment_id << " (" << board_idx << ") is out of range. Skipping this fragment..." << std::endl;
    } else {
      valid_fragment = true;
    }
  } else {
      if (fverbose) std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: fragment ID " << fragment_id << " is not valid. Skipping this fragment..." << std::endl;
  }

  if (valid_fragment) {
    fragment_indices[board_idx]++;  
    if (fverbose) std::cout << "\n > SBNDXARAPUCADecoder::decode_fragment: decoding V1740 CAEN fragment " << fragment_indices[board_idx] << " from the board " << board_idx << " (slot " << fboard_id_list[board_idx] << "):" << std::endl;

    // ===============  Accesses Event metadata and Event header for this fragment =============== //

    CAENV1740Fragment caen_fragment(fragment);
    CAENV1740FragmentMetadata const* metadata = caen_fragment.Metadata();
    uint32_t num_channels = metadata->nChannels;
    if (fverbose) std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: number of channels: " << num_channels << std::endl;

    // Accesses the event and header data of the CAEN fragment.
    CAENV1740Event const* event = caen_fragment.Event();
    CAENV1740EventHeader header = event->Header;
    
    // Gets the number of words of the header and the waveforms.
    uint32_t num_words_per_event = header.eventSize;
    size_t header_size = sizeof(CAENV1740EventHeader);
    uint32_t num_words_per_header = header_size / sizeof(uint32_t);
    uint32_t num_words_per_wvfms = (num_words_per_event - num_words_per_header);

    uint32_t num_bits_per_all_wvfms = num_words_per_wvfms * BITS_PER_WORD;
    uint32_t num_samples_per_all_wvfms =  num_bits_per_all_wvfms / BITS_PER_SAMPLE;
    uint32_t num_remaining_bits = num_bits_per_all_wvfms % BITS_PER_SAMPLE;
    uint32_t num_samples_per_wvfm = num_samples_per_all_wvfms / num_channels;
    uint32_t num_samples_per_group = num_samples_per_wvfm * NUM_CHANNELS_PER_GROUP;
    uint32_t num_nominal_samples_per_wvfm = metadata->nSamples;

    if (fverbose | fdebug_waveforms) {
      if (num_nominal_samples_per_wvfm == num_samples_per_wvfm) {
        std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: [NOMINAL FRAGMENT] " << num_samples_per_wvfm << " samples/waveform." << " (" << num_samples_per_group << " samples per group - 8 channels per group -)." << std::endl;
      } else {
        std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: [EXTENDED FRAGMENT] " << num_samples_per_wvfm << " samples/waveform." << " (" << num_samples_per_group << " samples per group - 8 channels per group -)." << std::endl;
      }
      std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: nominal number of samples per waveform: " << num_nominal_samples_per_wvfm << "." << std::endl;
      std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: number of words for this fragment: " << num_words_per_event << " (Header: " << num_words_per_header << ", Waveform: " << num_words_per_wvfms << ") words." << std::endl;
    }

    if (fdebug_waveforms) {
      std::cout << "\t Number of bits for all the waveforms of this fragment: " << BITS_PER_WORD << "\t" << num_bits_per_all_wvfms << std::endl;
      std::cout << "\t Number of samples for all the waveforms of this fragment: " << num_samples_per_all_wvfms << std::endl;
      std::cout << "\t Number of remaining bits for this fragment: " << num_remaining_bits << std::endl;
      std::cout << "\t Number of samples per wvfm (this fragment): " << num_samples_per_wvfm << std::endl;    
      std::cout << "\t Number of samples per group (this fragment): " << num_samples_per_group << std::endl;
    }

    // ===============  Extracts timing information for this fragment =============== //

    uint64_t frag_timestamp = fragment.timestamp(); // ns.
    uint32_t TTT_ticks = header.triggerTime();
    int64_t TTT_end_ns = TTT_ticks * NANOSEC_PER_TICK; // ns.

    if (fdebug_timing) {
      std::cout << "\t\t TTT header.extendedTriggerTime() [TTT_ticks] = " << header.extendedTriggerTime() << " ticks. \t TTT_end_ns = " << print_timestamp(header.extendedTriggerTime() * NANOSEC_PER_TICK) << "." << std::endl;
      std::cout << "\t\t TTT header.triggerTimeRollOver(): " << header.triggerTimeRollOver() << std::endl;
    }

    //// ===============  Start decoding the waveforms =============== //
    std::vector <std::vector <uint16_t> > fragment_wvfms(num_channels, std::vector<uint16_t>(num_samples_per_wvfm, 0));
    decode_waveforms(fragment, fragment_wvfms, header_size, num_channels, num_samples_per_wvfm, num_words_per_wvfms, num_samples_per_group);
    
    double ini_wvfm_timestamp = 0;
    double end_wvfm_timestamp = 0;
    
    if (fverbose) {
      std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: processing the decoded fragment and combines the extended ones to their nominal ones if needed." << std::endl;
    }

    if (fcombine_ext_frag) {

      // Combination variables and checks.

      bool is_nominal = (num_nominal_samples_per_wvfm == num_samples_per_wvfm);
      bool is_first = (fragment_indices[board_idx] == 0);

      int32_t frag_length = num_samples_per_wvfm * fns_per_sample; // ns.

      // - Computation of the difference w.r.t. previous TTT difference.
      int32_t TTT_dif = 0;
      if (prev_TTT > TTT_end_ns) {
        if (fverbose | fdebug_timing) std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: CAEN TTT rollover occurred." << std::endl;
        TTT_dif = prev_TTT - (NANOSEC_IN_SEC - TTT_end_ns);
      } else {
        TTT_dif = TTT_end_ns - prev_TTT;
      }

      // - Computation of the difference between TTTs difference and the length of the fragment in ns (to detect jittering between fragments).
      int32_t J = TTT_dif - frag_length;

      bool dump_comb_wvfms = !is_first && (is_nominal || (!is_nominal && (TTT_dif > (frag_length + fallowed_jittering))));

      if (is_first) {
        first_frag_idx = fragment_indices[board_idx];
        first_TTT = TTT_end_ns;
        first_frag_timestamp = frag_timestamp;
      }

      if (dump_comb_wvfms) {
        shift_time(TTT_ticks, first_TTT, first_frag_timestamp, timestamp, num_nominal_samples_per_wvfm, ini_wvfm_timestamp, end_wvfm_timestamp, appended_samples);
        dump_waveforms(prod_wvfms, wvfms, first_frag_idx, board_idx, num_channels, ini_wvfm_timestamp, end_wvfm_timestamp);
        first_frag_idx = fragment_indices[board_idx];
        first_TTT = TTT_end_ns;
        first_frag_timestamp = frag_timestamp;
        if (fdebug_jittering) std::cout << "NC - ";
      } else {
        if (fdebug_jittering) std::cout << "C -  ";
      }
      append_waveforms(wvfms, fragment_wvfms, num_channels);
      appended_samples = wvfms[0].size() - num_nominal_samples_per_wvfm;
      
      if (last_one) {
        if (fdebug_extended_fragments) std::cout << "\t\t LAST fragment " << std::endl;
        shift_time(TTT_ticks, first_TTT, first_frag_timestamp, timestamp, num_nominal_samples_per_wvfm, ini_wvfm_timestamp, end_wvfm_timestamp, appended_samples);
        dump_waveforms(prod_wvfms, wvfms, first_frag_idx, board_idx, num_channels, ini_wvfm_timestamp, end_wvfm_timestamp);
      }

      if (fdebug_jittering) {
        if (is_first) {
          std::cout << "\t\t FIRST ";
        }
        if (is_nominal) {
          int32_t TTT_ini_ns = TTT_end_ns - static_cast<int32_t>(num_nominal_samples_per_wvfm * fns_per_sample);
          std::cout << "NOMINAL fragment " << fboard_id_list[board_idx] << " - " << fragment_indices[board_idx] << " (" << num_samples_per_wvfm << "): [" << TTT_ini_ns << ", " << TTT_end_ns << "] diff with prev: " << TTT_dif << " ns, length: " << frag_length << " ns, diff_with_length (jitt): " <<  J << std::endl;
        } else {
          int32_t TTT_ini_ns = TTT_end_ns - static_cast<int32_t>(num_nominal_samples_per_wvfm * fns_per_sample);
          std::cout << "EXTENDED fragment " << fboard_id_list[board_idx] << " - " << fragment_indices[board_idx] << " (" << num_samples_per_wvfm << "): [" << TTT_ini_ns << ", " << TTT_end_ns << "] diff with prev: " << TTT_dif << " ns, length: " << frag_length << " ns, diff_with_length (jitt): " <<  J << std::endl;
        }
      }

      // WARNINGS
      if (TTT_dif < frag_length - fallowed_jittering) {
        if (!is_first) {
          if (!is_nominal) std::cout << "\t\t WARNING: EXTENDED fragment too close! This fragment is being combined." << std::endl;
          if (is_nominal) std::cout << "\t\t WARNING: NOMINAL fragment too close! This fragment is not being combined." << std::endl;
        }
      }

      prev_TTT = TTT_end_ns;
    
    } else { // Combination of extended fragments disabled.
      first_frag_idx = fragment_indices[board_idx];
      shift_time(TTT_ticks, TTT_end_ns, frag_timestamp, timestamp, num_samples_per_wvfm, ini_wvfm_timestamp, end_wvfm_timestamp, appended_samples);
      dump_waveforms(prod_wvfms, fragment_wvfms, first_frag_idx, board_idx, num_channels, ini_wvfm_timestamp, end_wvfm_timestamp);
    }
  }

}

// ===============  Timing functions =============== //

/**
  * @brief This function shifts the initial and end timestamps of a waveform based on the provided timing information.
  * 
  * @param[in] TTT_ticks The trigger time tag in ticks from the CAEN V1740 header.
  * @param[in] TTT_end_ns The end time of the Trigger Time Tag (TTT) in nanoseconds.
  * @param[in] frag_timestamp The timestamp of the fragment in nanoseconds.
  * @param[in] timestamp The reference timestamp (from FRAMESHIFT or CAEN-only) in nanoseconds.
  * @param[in] num_samples_per_wvfm The number of samples per waveform.
  * @param[out] ini_wvfm_timestamp The initial timestamp of the waveform in microseconds (output).
  * @param[out] end_wvfm_timestamp The end timestamp of the waveform in microseconds (output).
  * 
  * @details 
  * This function calculates the initial and end timestamps for a waveform based on the provided timing information. It takes into account
  * potential rollovers in the trigger time tag and adjusts the timestamps accordingly. The function supports different timing frames, including
  * FRAMESHIFT and CAEN-only timing. The calculated timestamps are returned in microseconds.
  *
 */
void sbndaq::SBNDXARAPUCADecoder::shift_time(uint64_t TTT_ticks, int64_t TTT_end_ns, uint64_t frag_timestamp, uint64_t timestamp, uint32_t num_samples_per_wvfm, double& ini_wvfm_timestamp, double& end_wvfm_timestamp, size_t& appended_samples) {
  
  int64_t pulse_duration_ns = num_samples_per_wvfm * fns_per_sample; // ns.
  int64_t frag_timestamp_s = frag_timestamp / NANOSEC_IN_SEC; // s.
  int64_t frag_timestamp_ns = frag_timestamp % NANOSEC_IN_SEC; // ns.

  // Gets the UNIX TTT timestamp.
  uint64_t TTT_UNIX_timestamp = 0;
  // If the fragment timestamp is greater than the TTT end timestamp, it means that rollover occurred.
  if (frag_timestamp_ns > TTT_end_ns) {
    if (fverbose | fdebug_timing) std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: CAEN TTT rollover occurred w.r.t. the fragment timestamp (FTS)." << std::endl;
    TTT_UNIX_timestamp = (frag_timestamp_s + 1) * NANOSEC_IN_SEC + TTT_end_ns;
  } else {
    TTT_UNIX_timestamp = frag_timestamp_s * NANOSEC_IN_SEC + TTT_end_ns;
  }

  int64_t ref_timestamp = 0;
  int64_t appended_ns = static_cast<int64_t>(appended_samples) * static_cast<int64_t>(fns_per_sample); // this is just for the debug output.

  // If an frameshift timestamp was found it restarts the time from it. Otherwise the CAEN time frame is assigned.
  if (factive_timing_frame != CAEN_ONLY_TIMING) {
    ref_timestamp = signed_difference_UTC_timestamp(TTT_UNIX_timestamp, timestamp); // ns.
    ini_wvfm_timestamp = (ref_timestamp - pulse_duration_ns) * NANOSEC_TO_MICROSEC; // us.
    end_wvfm_timestamp = (ref_timestamp + appended_ns) * NANOSEC_TO_MICROSEC; // us.
  } else {
    ref_timestamp = TTT_UNIX_timestamp; // ns.

    ini_wvfm_timestamp = ((ref_timestamp - pulse_duration_ns) % NANOSEC_IN_SEC) * NANOSEC_TO_MICROSEC; // ns.
    end_wvfm_timestamp = ((ref_timestamp + appended_ns)% NANOSEC_IN_SEC) * NANOSEC_TO_MICROSEC; // us.
  }
  appended_samples = 0;
  if (fdebug_timing) {
    std::cout << std::fixed << std::setprecision(0);
    std::cout << "\t\t ns/tick = " << NANOSEC_PER_TICK << ", ns/sample = " << fns_per_sample << std::endl;
    std::cout << "\t\t TTT header.TriggerTime() [TTT_ticks] = " << TTT_ticks << " ticks. \t TTT_end_ns = " << print_timestamp(TTT_end_ns) << "." << std::endl;
    std::cout << "\t\t Full Fragment timestamp: " << print_timestamp(frag_timestamp) << " = " << frag_timestamp_s << " s " << frag_timestamp_ns << " ns." << std::endl;
    std::cout << "\t\t Full TTT - fragment timestamp = "<< abs_difference(TTT_UNIX_timestamp, frag_timestamp) << " ns." << " Post-percent: " << (double(abs_difference(TTT_UNIX_timestamp, frag_timestamp)) / double(pulse_duration_ns)) * 100 << "%." << std::endl;
    if (factive_timing_frame == FRAMESHIFT_TIMING) {
      std::cout << "\t FRAMESHIFT timestamp of the fragment: " << std::endl;
      std::cout << "\t\t Full UTC FRAMESHIFT timestamp: " << print_timestamp(timestamp) << "." << std::endl;
      std::cout << "\t\t FRAMESHIFT difference applied to the CAEN frame (UNIX timestamps): " << print_timestamp(TTT_UNIX_timestamp) << " - " << print_timestamp(timestamp) <<  " = " << ref_timestamp << " ns." << std::endl;
    } else {
      std::cout << "\t CAEN trigger timestamp (TTT) of the fragment: " << std::endl;
      std::cout << "\t\t Full UTC TTT timestamp: " << print_timestamp(TTT_UNIX_timestamp) << " = " << TTT_UNIX_timestamp / NANOSEC_IN_SEC << " s " << TTT_end_ns << " ns." << std::endl;
    }
  }

  if (fverbose | fdebug_timing) {
    std::cout << std::fixed << std::setprecision(3);
    if (factive_timing_frame == FRAMESHIFT_TIMING) {
      std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: FRAMESHIFT time window of " << end_wvfm_timestamp - ini_wvfm_timestamp << " us: [" << ini_wvfm_timestamp << ", " << end_wvfm_timestamp << "] us." << std::endl;
    } else { // CAEN_ONLY_TIMING
      std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: CAEN time window of " << end_wvfm_timestamp - ini_wvfm_timestamp << " us: [" << ini_wvfm_timestamp << ", " << end_wvfm_timestamp << "] us." << std::endl;
    }
    std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: TTT_end_ticks = " << TTT_ticks << " ticks. \t TTT_end_ns = " << print_timestamp(TTT_end_ns) << "." << std::endl;
  }
}

/**
  * @brief Searches for the frameshift timestamp in the event if any frameshift product is found and returns it as a TimingReferenceInfo object.
  * @param[in] e The event to be processed.
  * @param[in,out] timestamp The frameshift timestamp (if found).
  * @param[in,out] timing_type The type of the frameshift timestamp (if found).
  * @param[in,out] timing_channel The channel of the frameshift timestamp (if found).
  * @return A unique pointer to a TimingReferenceInfo object containing the frameshift timestamp information (if found), or nullptr if no valid frameshift product is found.
  * @details It searches for the frameshift products in the event and looks for the default frameshift timestamp, type and channel. If any valid frameshift product is found, it returns its information as a TimingReferenceInfo object.
 */
std::unique_ptr<raw::TimingReferenceInfo> sbndaq::SBNDXARAPUCADecoder::get_frameshift_timestamp(art::Event& e, uint64_t& timestamp) {
  std::unique_ptr<raw::TimingReferenceInfo> fs_timing_ref_info = nullptr;

  art::Handle<sbnd::timing::FrameShiftInfo> frameshiftHandle;    
  e.getByLabel(fframeshift_product_name, frameshiftHandle);

  if (fverbose || fdebug_frameshift_handle) std::cout << "\n > SBNDXARAPUCADecoder::get_frameshift_timestamp: Frameshift timing frame selected. Searching for Frameshift products..." << std::endl;
  
  if (frameshiftHandle.isValid()) {
    
    uint16_t timing_type    = frameshiftHandle->TimingTypeDefault();
    uint16_t timing_channel = frameshiftHandle->TimingChannelDefault();

    if (timing_type != sbnd::timing::kNoShiftType) { // Only if timing type is valid, the timestamp is considered valid.
      timestamp = frameshiftHandle->FrameDefault();
      fs_timing_ref_info = std::make_unique<raw::TimingReferenceInfo>(timing_type, timing_channel);
    } else {
      timestamp = 0;
    }
        
  } else {
    if (fdebug_frameshift_handle) std::cout << "\n\tFrameshift handle not valid for " << fframeshift_product_name << "." << std::endl;
    throw std::runtime_error("XA Decoder: Frame Shift Info object is invalid, check data quality");
  }

  return fs_timing_ref_info;
}

// ===============  Decodes the waveforms =============== //

/**
 * @brief Decodes the waveforms from a CAEN V1740 fragment (binary decoding stage).
 * 
 * @param[in] fragment The input CAEN V1740 fragment containing raw data to be decoded.
 * @param[out] wvfms A 2D vector where the decoded waveforms will be stored. Each inner vector corresponds to a channel's waveform.
 * @param[in] header_size The size of the event header in bytes.
 * @param[in] num_channels The number of channels in the fragment.
 * @param[in] num_samples_per_wvfm The number of samples per waveform for each channel.
 * @param[in] num_words_per_wvfms The total number of 32-bit words containing waveform data in the fragment.
 * @param[in] num_samples_per_group The number of samples per group of channels (8 channels per group).
 * 
 * @details This function reads raw 32-bit words from the fragment, storing them in a buffer, and extracts 12-bit samples. 
 * It assigns each sample to the appropriate channel and sample index based on its position in the sequence. The decoding process includes:
 * - Initializing a buffer to hold incoming data and tracking the number of bits currently stored.
 * - Iterating over each 32-bit word in the waveform data section of the fragment, adding it to the buffer.
 * - Extracting 12-bit samples from the buffer as long as there are enough bits available, and assigning them to their respective channels and sample indices using calculated formulas.
 * The function ensures that all samples are correctly mapped to their channels, taking into account the grouping of channels and the interleaving of samples.
 * @note The function assumes that the input fragment is valid and contains the expected structure for a CAEN V1740 device.
 * @see SBN Document 38475-v1 for more details on the binary decoding.
 */
void sbndaq::SBNDXARAPUCADecoder::decode_waveforms(const artdaq::Fragment& fragment, std::vector<std::vector<uint16_t>>& wvfms, size_t header_size, uint32_t num_channels, uint32_t num_samples_per_wvfm, uint32_t num_words_per_wvfms, uint32_t num_samples_per_group) {
  // ===============  Start decoding the waveforms =============== //
  if (fverbose) std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: binary decoding of the waveforms starting... " << std::endl;
  
  // Absolute sample number [0, TOTAL_NUM_SAMPLES] where TOTAL_NUM_SAMPLES is the total number of samples stored for an event.
  uint32_t S = 0;
  // Buffer variables.
  uint64_t buffer = 0;
  uint32_t bits_in_buffer = 0;

  // Data pointer to the beggining of the waveforms stores in the event.
  const uint32_t* data_ptr = reinterpret_cast<const uint32_t*>(fragment.dataBeginBytes() + header_size);
  // Accesses each word, stores it in the buffer and then the samples are extracted from the buffer.
  for (size_t j = 0; j < num_words_per_wvfms; j++) {
    uint64_t word = read_word(data_ptr);

    // Adds the new word to the buffer and increments the number of bits stored in it.
    if (fdebug_buffer) std::cout << buffer << "[word: " << word << "]" << std::endl;
    buffer |= word << bits_in_buffer;
    bits_in_buffer += BITS_PER_WORD; // bytes * 8 bits/byte
    if (fdebug_buffer) std::cout << "  +" << buffer << " [bits in buffer: "<< bits_in_buffer << "]" << std::endl;

    // Obtains 12-bit sequences from the buffer and assigns each sample to the channel and channel sample it belongs to. 
    while (bits_in_buffer >= BITS_PER_SAMPLE) {
      // Computes board channel, channel sample and group channel and assigns the sample to those indices.
      uint32_t g = (S / num_samples_per_group);                                                                                       // Group index.
      uint32_t c = ((S / NUM_CONSECUTIVE_SAMPLES) % NUM_CHANNELS_PER_GROUP) + g * NUM_GROUPS;                                         // Channel index.
      uint32_t s = (S % NUM_CONSECUTIVE_SAMPLES) + ((S / NUM_SAMPLES_PER_ROUND) * NUM_CONSECUTIVE_SAMPLES) % num_samples_per_wvfm;    // Sample/channel index.
      uint16_t sample = get_sample(buffer, BITS_PER_SAMPLE - 1, 0);
      wvfms[c][s] = sample;
      if (fdebug_waveforms) std::cout << "\tSample: " << sample << "\tg: " << g <<  "\tch: " << c << "\ts:" << s << "\tS: " << S << std::endl;
      
      // Updates the buffer status removing the read bits and decreasing the number of bits stored in it.
      buffer >>= BITS_PER_SAMPLE;
      bits_in_buffer -= BITS_PER_SAMPLE;
      if (fdebug_buffer) std::cout << "  -" << buffer << " [bits in buffer: "<< bits_in_buffer << "]" << std::endl;
      
      // Increments the absolute sample step.
      S++;
    }
  }
}

/**
 * @brief Extract a sample from a 64-bit buffer using the specified bit positions.
 *
 * @param[in] buffer An unsigned 64-bit integer which represents a temporal buffer for the read words and where the samples are extracted from. 
 * @param[in] msb An unsigned 32-bit integer representing the most significative bit (MSB) where the readout from the buffer paramter.
 * @param[in] lsb An unsigned 32-bit integer representing the less significative bit (LSB) from we end read
 *
 * @details The function shifts the buffer to the right by the number of positions specified by `lsb` so that the least significant bit of the 
 * sample aligns with bit 0. It then applies a mask to isolate the bits between `lsb` and `msb`, inclusive.
 *
 * @return The extracted sample as a 16-bit unsigned integer.
 */
uint16_t sbndaq::SBNDXARAPUCADecoder::get_sample(uint64_t buffer, uint32_t msb, uint32_t lsb) {
  uint64_t mask = (1U << (msb - lsb + 1)) - 1;
  uint64_t sample = buffer >> lsb;
  return sample & mask;
}

/**
 * @brief Read a 32-bit word from the data pointer and advances the pointer. 
 *
 * @param[in, out] data_ptr A reference to a pointer pointing to the current position in the data.
 *
 * @details This function retrieves a 32-bit word from the memory location pointed to by `data_ptr`. After reading, it advances `data_ptr` to 
 * the next 32-bit word location.
 *
 * @return The 32-bit word read from the location pointed to by `data_ptr`.
 */
uint32_t sbndaq::SBNDXARAPUCADecoder::read_word(const uint32_t* & data_ptr) {
  uint32_t word = *data_ptr;
  data_ptr += 1;
  return word;
}

/**
 * @brief Generates a unique global channel identifier using the board slot and the channel number of that board.
 *
 * @param[in] board Index of the board in `fboard_id_list` from which to derive the board slot.
 * @param[in] board_channel The specific channel number on the given board.
 *
 * @details This function computes a `channel_id` by combining the board slot and the specific 
 * channel number on that board. 
 * The unique identifier `channel_id` (\f$ CH_{ID} $\f) is computed as follows:
 * \f[
 * CH\_{ID} = B\_{ID} \times 100 + CH\_{B}
 * \f]
 *
 * Where:
 * - \f$ B\_{ID} \f$ is the fragment ID retrieved from `fboard_id_list` based on the slot.
 * - \f$ CH\_B \f$ is the channel number on that board.
 *
 * @return A unique identifier for the specified channel as an unsigned integer.
 */
unsigned int sbndaq::SBNDXARAPUCADecoder::get_channel_id(unsigned int board, unsigned int board_channel) {
  unsigned int channel_id = fboard_id_list[board] * 100 + board_channel;
  return channel_id;
}

// ===============  Combines the waveforms from extended fragments =============== //

/**
 * @brief Combines the waveforms from the current fragment with the previously stored waveforms.
 * @param[in,out] wvfms A 2D vector containing the (combined if it was needed before) waveforms.
 * @param[in] fragment_wvfms A 2D vector containing the waveforms from the current fragment to be combined.
 * @param[in] num_channels The number of channels per board.
 *
 * @details
 * The function performs the following steps:
 * 1. Checks if the `wvfms` vector is empty. If it is, it resizes it to accommodate `num_channels` channels.
 * 2. Iterates over each channel from 0 to `num_channels - 1`.
 * 3. For each channel, it appends the samples from `fragment_wvfms` to the corresponding channel in `wvfms`.
 * 
 * This approach ensures that waveforms from multiple fragments are concatenated correctly, maintaining the order of samples for each channel.
 * 
 * @pre The `fragment_wvfms` vector should contain waveforms for all channels of the board being processed.
 * @pre The `wvfms` vector should be either empty or already contain waveforms for all channels of the board being processed.
 */
void sbndaq::SBNDXARAPUCADecoder::append_waveforms(std::vector<std::vector<uint16_t>>& wvfms, const std::vector<std::vector<uint16_t>>& fragment_wvfms, uint32_t num_channels) {
  if (fdebug_extended_fragments) std::cout << "  > SBNDXARAPUCADecoder::append_waveforms: combining waveforms from extended fragments..." << std::endl;
  if (wvfms.empty()) {
    if (fdebug_extended_fragments) {
      std::cout << "\t\t Empty waveforms, resizing to " << num_channels << " channels." << std::endl;
    }
    wvfms.resize(num_channels);
    if (fverbose | fdebug_extended_fragments) { 
      std::cout << "\t\t Waveforms size BEFORE combining = " << wvfms.size() << " x " << wvfms[0].size() << std::endl;
    }
  }
  for (uint32_t ch = 0; ch < num_channels; ch++) {
    wvfms[ch].insert(wvfms[ch].end(), fragment_wvfms[ch].begin(), fragment_wvfms[ch].end());
  }
  if (fverbose | fdebug_extended_fragments) { 
    std::cout << "\t\t Waveforms size AFTER combining = " << wvfms.size() << " x " << wvfms[0].size() << std::endl;
  }
}

// ===============  Dumps the decoded waveforms =============== //

/**
 * @brief Dump products into a `raw::OpDetWaveform` object and into a debug histogram file.
 * @param[in,out] prod_wvfms A reference to the vector where the produced `raw::OpDetWaveform` objects are dumped into products.
 * @param[in,out] wvfms A 2D vector containing the (combined if needed) waveforms.
 * @param[in,out] fragment_indices A reference to a vector keeping track of the number of fragments decoded per board.
 * @param[in] board_idx The board index (position in the list of boards).
 * @param[in] num_channels The number of channels per board.
 * @param[in] ini_wvfm_timestamp The initial timestamp of the waveform in microseconds.
 * @param[in] end_wvfm_timestamp The final timestamp of the waveform in microseconds.
 *
 * @details
 * The function performs the following steps:
 * 1. Determines the number of debug waveforms to be stored based on the configuration parameter `fstore_debug_waveforms`.
 *    - If `fstore_debug_waveforms` is set to -1, all channels are considered for debug storage.
 *    - Otherwise, it takes the minimum between `num_channels` and `fstore_debug_waveforms`.
 * 2. Iterates over each channel up to the determined number of debug waveforms:
 *    - Calls `save_prod_wvfm` to convert and store the waveform in the products.
 *    - Calls `save_debug_wvfm` to save the waveform as a histogram for debugging purposes.
 * 3. For any remaining channels beyond the debug limit, it only calls `save_prod_wvfm` to store the waveform in the products.
 * 4. Clears the `wvfms` vector to free up memory after processing.
 * 
 * @pre ini_wvfm_timestamp and end_wvfm_timestamp is assumed to be given in microseconds when the timing frame is not CAEN_ONLY_TIMING.
 * @pre The `wvfms` vector should contain waveforms for all channels of the board specified by `board_idx`.
 * @pre The `fragment_indices` vector should have been initialized with a size equal to the number of boards being processed.
 * @pre The `prod_wvfms` vector should be ready to accept new `raw::OpDetWaveform` objects.
 *
 * @see raw::OpDetWaveform
 * @see save_prod_wvfm
 * @see save_debug_wvfm
 */
void sbndaq::SBNDXARAPUCADecoder::dump_waveforms(std::vector <raw::OpDetWaveform> & prod_wvfms, std::vector<std::vector<uint16_t>>& wvfms, size_t first_frag_idx, size_t board_idx, uint32_t num_channels, double ini_wvfm_timestamp, double end_wvfm_timestamp) {
    
  // The decoded waveforms are dumped into two products:
  // - A xarapucadecoder-art.root file with the OpDetWaveforms as the product of this producer for further analysis.
  // - A decoder_hist.root file gathering a waveform histograms.
  if (fverbose) std::cout << "  > SBNDXARAPUCADecoder::decode_fragment: binary decoding complete, dumping products..." << std::endl;
  
  uint32_t num_debug_wvfms;

  if (fstore_debug_waveforms == -1) {
    num_debug_wvfms = num_channels;
  } else {
    num_debug_wvfms = std::min<size_t>(num_channels, fstore_debug_waveforms);
  }

  uint32_t ch;

  for (ch = 0; ch < num_debug_wvfms; ch++) {
    save_prod_wvfm(board_idx, ch, ini_wvfm_timestamp, wvfms, prod_wvfms);
    save_debug_wvfm(board_idx, first_frag_idx, ch, ini_wvfm_timestamp, end_wvfm_timestamp, wvfms);
  }

  for (;ch < num_channels; ch++) {
    save_prod_wvfm(board_idx, ch, ini_wvfm_timestamp, wvfms, prod_wvfms);
  }

  wvfms.clear();

}

/**
 * @brief Converts a production waveform from raw ADC data into a `raw::OpDetWaveform` object,
 * assigning it a global channel ID and timestamp, and appends it to the output collection.
 *
 * @param[in] b The board index (position in the list of boards).
 * @param[in] ch The channel index (channel number from which the waveform is extracted).
 * @param[in] ini_wvfm_timestamp The initial timestamp of the waveform in microseconds.
 * @param[in] wvfms A 2D vector containing the waveforms. Each inner vector corresponds to a channel,
 * and each element of the inner vector represents a sample (ADC count).
 * @param[out] prod_wvfms A reference to the vector where the produced `raw::OpDetWaveform` objects
 * will be stored.
 *
 * @details
 * The function performs the following steps:
 * 1. Determines the global channel ID for the specified board and channel using `get_channel_id`.
 * 2. Creates a `raw::OpDetWaveform` object with the initial timestamp, global channel ID, and waveform data.
 * 3. Appends the `raw::OpDetWaveform` object to the provided `prod_wvfms` collection.
 * 
 * @pre ini_wvfm_timestamp is assumed to be given in microseconds when the timing frame is not CAEN_ONLY_TIMING.
 *
 * @see raw::OpDetWaveform
 */
void sbndaq::SBNDXARAPUCADecoder::save_prod_wvfm(size_t board_idx, size_t ch, double ini_wvfm_timestamp, const std::vector <std::vector <uint16_t> > & wvfms, std::vector <raw::OpDetWaveform> & prod_wvfms) {
  unsigned int channel_id = get_channel_id(board_idx, ch);
  raw::OpDetWaveform waveform(ini_wvfm_timestamp, channel_id, wvfms[ch]);
  if (fdebug_waveforms) std::cout << "Pushing waveform from board " << board_idx << " (slot " << fboard_id_list[board_idx] << ") channel " << ch << " (ch_id " << channel_id << ")" << std::endl;
  prod_wvfms.push_back(waveform);
}

/**
 * @brief Saves debug waveform as a histogram for debugging purposes, based on the waveform data provided. 
 * The histogram is labeled with event number, fragment, board slot ID and channel information.
 *
 * @param[in] board_idx The board index (position in the list of boards).
 * @param[in] fragment_idx The fragment index (order in decoding).
 * @param[in] ch The channel index (channel number from which the waveform is extracted).
 * @param[in] ini_wvfm_timestamp The initial timestamp of the waveform.
 * @param[in] end_wvfm_timestamp The final timestamp of the waveform.
 * @param[in] wvfms A 2D vector containing the waveforms. Each inner vector corresponds to a channel,
 * and each element of the inner vector represents a sample (ADC count).
 *
 * @details
 * The function generates a histogram with:
 * - X-axis representing time in microseconds if the timing frame is from the FRAMESHIFT reference, otherwise in samples.
 * - Y-axis representing ADC counts.
 * The histogram is stored using ROOT's `TFileService`.
 * 
 * @pre ini_wvfm_timestamp and end_wvfm_timestamp are assumed to be given in microseconds when the timing frame is not CAEN_ONLY_TIMING.
 *
 * @see TH1I, TFileService
 */

void sbndaq::SBNDXARAPUCADecoder::save_debug_wvfm(size_t board_idx, size_t fragment_idx, int ch, double ini_wvfm_timestamp, double end_wvfm_timestamp, const std::vector <std::vector <uint16_t> > & wvfms) {
  std::stringstream hist_name("");
  hist_name << "Event " << fevent_counter << " CH " << ch << " [frag " << fragment_idx << ", board " << board_idx << " (slot " << fboard_id_list[board_idx] << ") ] waveform";

  if (factive_timing_frame != CAEN_ONLY_TIMING) {
    TH1I* hist = tfs->make<TH1I>(hist_name.str().c_str(), hist_name.str().c_str(), wvfms[ch].size(), ini_wvfm_timestamp, end_wvfm_timestamp);
    hist->GetYaxis()->SetTitle("ADCs");
    if (factive_timing_frame == FRAMESHIFT_TIMING) {
      hist->GetXaxis()->SetTitle("Time w.r.t. Frameshift reference [us]");
    }
    for (size_t i = 0; i < wvfms[ch].size(); i++) {
      hist->SetBinContent(i+1, wvfms[ch][i]);
    }
  } else {
    TH1I* hist = tfs->make<TH1I>(hist_name.str().c_str(), hist_name.str().c_str(), wvfms[ch].size(), 0,  wvfms[ch].size());
    hist->GetYaxis()->SetTitle("ADCs");
    hist->GetXaxis()->SetTitle("Samples");
    for (size_t i = 0; i < wvfms[ch].size(); i++) {
      hist->SetBinContent(i+1, wvfms[ch][i]);
    }
  }

}

// ==================== Auxiliary functions ====================  //

/**
 * @brief Returns the signed difference between two timestamps (t1 - t2).
 * @param[in] t1 The first timestamp in nanoseconds.
 * @param[in] t2 The second timestamp in nanoseconds.
 * @return The signed difference between the two timestamps (t1 - t2) in nanoseconds.
 * @pre The timestamp is given in nanoseconds and the maximum value is less than 2^63 ns.
 */
int64_t sbndaq::SBNDXARAPUCADecoder::signed_difference_UTC_timestamp(uint64_t t1, uint64_t t2) {
  int64_t signed_diff = 0;
  
  if (t2 < t1) {
    signed_diff = (t1 - t2);
  } else {
    signed_diff = (t2 - t1) * -1;
  }
  
  return signed_diff;
}

/**
 * @brief Returns the absolute difference between two timestamps.
 * @param[in] t1 The first timestamp in nanoseconds.
 * @param[in] t2 The second timestamp in nanoseconds.
 * @return The absolute difference between the two timestamps in nanoseconds.
 * @pre The timestamp is given in nanoseconds and the maximum value is less than 2^63 ns.
 */
uint64_t sbndaq::SBNDXARAPUCADecoder::abs_difference(uint64_t t1, uint64_t t2) {
  uint64_t abs_diff = 0;
  
  if (t2 < t1) {
    abs_diff = (t1 - t2);
  } else {
    abs_diff = (t2 - t1);
  }
  
  return abs_diff;
}

/**
 * @brief Formats a timestamp in nanoseconds into a easily readable string format.
 * @param[in] timestamp The timestamp in nanoseconds to be formatted.
 * @return A string representation of the timestamp in the format "(seconds)nanoseconds ns".
 * @details The function divides the input timestamp by 1,000,000,000 to obtain the seconds component and uses the modulus operator to get the remaining nanoseconds.
 */
std::string sbndaq::SBNDXARAPUCADecoder::print_timestamp(uint64_t timestamp) {
  return "(" + std::to_string(timestamp / NANOSEC_IN_SEC) + ")" + std::to_string(timestamp % NANOSEC_IN_SEC) + " ns";
}

DEFINE_ART_MODULE(sbndaq::SBNDXARAPUCADecoder)
