////////////////////////////////////////////////////////////////////////
//// Class:       SBNDFlashFinder
//// Module Type: producer
//// File:        SBNDFlashFinder_module.cc
////
//// Adapted form ICARUSFlashFinder by Kazuhiro Terao
//////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include "art/Utilities/make_tool.h"

#include "lardataobj/RecoBase/OpHit.h"
#include "lardataobj/RecoBase/OpFlash.h"
#include "lardata/Utilities/AssociationUtil.h"

#include <memory>
#include <string>
#include "sbndcode/OpDetReco/OpFlash/FlashFinder/FlashFinderManager.h"
#include "sbndcode/OpDetReco/OpFlash/FlashFinder/FlashFinderFMWKInterface.h"
#include "sbndcode/OpDetReco/OpFlash/FlashFinder/PECalib.h"
#include "sbndcode/OpDetReco/OpFlash/FlashTools/FlashGeoBase.hh"
#include "sbndcode/OpDetReco/OpFlash/FlashTools/FlashT0Base.hh"
#include "sbndcode/OpDetReco/OpFlash/FlashTools/DriftEstimatorBase.hh"
#include "lardataobj/RawData/OpDetWaveform.h"


namespace opdet{

  class SBNDFlashFinder;

  class SBNDFlashFinder : public art::EDProducer {
  public:
    explicit SBNDFlashFinder(fhicl::ParameterSet const & p);
    // The destructor generated by the compiler is fine for classes
    // without bare pointers or other resource use.

    // Plugins should not be copied or assigned.
    SBNDFlashFinder(SBNDFlashFinder const &) = delete;
    SBNDFlashFinder(SBNDFlashFinder &&) = delete;
    SBNDFlashFinder & operator = (SBNDFlashFinder const &) = delete;
    SBNDFlashFinder & operator = (SBNDFlashFinder &&) = delete;

    // Required functions.
    void produce(art::Event & e) override;
    void ConstructSummedWaveforms(std::vector<raw::OpDetWaveform> InputChannels, 
      std::vector<std::vector<double>>& SummedWaveforms, std::vector<double>& SummedWaveformStartTimes, int TPC);

  private:

    ::lightana::FlashFinderManager _mgr;
    ::lightana::PECalib _pecalib;
    std::vector<std::string> _hit_producers;
    std::string _ophit_input_time;
    bool _use_t0tool;
    bool _correct_light_propagation;
    double _readout_delay;

    // Tool for calculating the OpFlash Y and Z centers
    std::unique_ptr<lightana::FlashGeoBase> _flashgeo;
    double fTickRate;
    int fPromptSamples;
    double _time_res;
    std::string fDecoWaveformInput;

    // Tool for calculating the OpFlash t0
    std::unique_ptr<lightana::FlashT0Base> _flasht0calculator;

    // Tool for light propagation correction
    std::unique_ptr<lightana::DriftEstimatorBase> _driftestimator;

    ::lightana::LiteOpHitArray_t GetAssociatedLiteHits(::lightana::LiteOpFlash_t lite_flash,
                                                       ::lightana::LiteOpHitArray_t lite_hits_v);

  };

  SBNDFlashFinder::SBNDFlashFinder(lightana::Config_t const & p)
  : EDProducer{p}
  // Initialize member data here.
  {
    _hit_producers = p.get<std::vector<std::string>>("OpHitProducers");

    auto const flash_algo  = p.get<std::string>("FlashFinderAlgo");
    auto const flash_pset = p.get<lightana::Config_t>("AlgoConfig");
    auto algo_ptr = ::lightana::FlashAlgoFactory::get().create(flash_algo,flash_algo);
    algo_ptr->Configure(flash_pset);
    _time_res= flash_pset.get<double>("TimeResolution");
    _mgr.SetFlashAlgo(algo_ptr);
    _pecalib.Configure(p.get<lightana::Config_t>("PECalib"));
    _ophit_input_time = p.get<std::string>("OpHitInputTime", "PeakTime");
    _use_t0tool = p.get<bool>("UseT0Tool", false);
    _readout_delay = p.get<double>("ReadoutDelay", 0);
    _correct_light_propagation = p.get<bool>("CorrectLightPropagation", false);
    fTickRate = p.get<double>("TickRate", 2.0e-3); //us
    fPromptSamples = p.get<int>("PromptSamples");
    fDecoWaveformInput = p.get<std::string>("DecoWaveformInput", "opdecopmt");

    auto const flashgeo_pset = p.get<lightana::Config_t>("FlashGeoConfig");
    _flashgeo = art::make_tool<lightana::FlashGeoBase>(flashgeo_pset);
    if(_use_t0tool){
      auto const flasht0_pset = p.get<lightana::Config_t>("FlashT0Config");
      _flasht0calculator = art::make_tool<lightana::FlashT0Base>(flasht0_pset);
    }

    if(_correct_light_propagation){
      auto const driftestimator_pset = p.get<lightana::Config_t>("DriftEstimatorConfig");
      _driftestimator = art::make_tool<lightana::DriftEstimatorBase>(driftestimator_pset);
    }

    produces< std::vector<recob::OpFlash>   >();
    produces< art::Assns <recob::OpHit, recob::OpFlash> >();
  }

  void SBNDFlashFinder::produce(art::Event & e)
  {
    _flashgeo->InitializeFlashGeoAlgo();

    // produce OpFlash data-product to be filled within module
    std::unique_ptr< std::vector<recob::OpFlash> > opflashes(new std::vector<recob::OpFlash>);
    std::unique_ptr< art::Assns <recob::OpHit, recob::OpFlash> > flash2hit_assn_v
      (new art::Assns<recob::OpHit, recob::OpFlash>);

    std::vector<art::Ptr<recob::OpHit>> ophit_v;

    ::lightana::LiteOpHitArray_t ophits;
    double trigger_time=1.1e20;

    for (auto producer : _hit_producers) {

      // load OpHits previously created
      art::Handle<std::vector<recob::OpHit> > ophit_h;
      e.getByLabel(producer, ophit_h);

      // make sure hits look good
      if(!ophit_h.isValid()) {
        std::cerr << "\033[93m[ERROR]\033[00m ... could not locate OpHit!" << std::endl;
        throw std::exception();
      }

      std::vector<art::Ptr<recob::OpHit>> temp_v;
      art::fill_ptr_vector(temp_v, ophit_h);
      ophit_v.insert(ophit_v.end(), temp_v.begin(), temp_v.end());
    }

    for(auto const oph : ophit_v) {
      ::lightana::LiteOpHit_t loph;
      if(trigger_time > 1.e20) trigger_time = oph->PeakTimeAbs() - oph->PeakTime();

      if(_ophit_input_time=="RiseTime") loph.peak_time = oph->StartTime()+oph->RiseTime();
      else if(_ophit_input_time=="StartTime") loph.peak_time = oph->StartTime();
      else loph.peak_time = oph->PeakTime();

      size_t opdet = ::lightana::OpDetFromOpChannel(oph->OpChannel());
      loph.pe = _pecalib.Calibrate(opdet,oph->Area());
      loph.channel = oph->OpChannel();
      ophits.emplace_back(std::move(loph));
    }

    auto flash_v = _mgr.RecoFlash(ophits);
    //OpFlash Prompt Fraction calculation
    art::Handle< std::vector< raw::OpDetWaveform > > wfHandle;
    e.getByLabel(fDecoWaveformInput, wfHandle);
    //*wfHandle acts like a vector of raw::OpDetWaveforms
    std::vector<std::vector<double>> SummedWaveforms;
    std::vector<double> SummedWaveformStartTimes;
    //Need some way to indicate TPC being run. Could use 
    ConstructSummedWaveforms((*wfHandle), SummedWaveforms, SummedWaveformStartTimes, flash_v[0].tpc);
    //Can loop over each flash and construct the prompt fraction for each bin
    for(auto& lflash :  flash_v) 
    {
      double flasht0 = lflash.time; //might need to add in trigger time
      //loop over the waveforms and find which one this flash slots into
      int IndexToGrab=0;
      for(int iWave=0; iWave<int(SummedWaveforms.size()); iWave++)
      {
        if(flasht0 > SummedWaveformStartTimes[iWave] + SummedWaveforms.size()*fTickRate ) continue;
        else
        { 
          IndexToGrab=iWave; 
          break; // found the right waveform 
        }
      }
      //Get flash width (in samples?)
      double width = lflash.time_err*2*_time_res; //us width
      int InitialSample = (flasht0-SummedWaveformStartTimes[IndexToGrab])/fTickRate;
      int FinalSample = (flasht0+width-SummedWaveformStartTimes[IndexToGrab])/fTickRate;
      double PromptFraction=1;
      if(FinalSample - InitialSample > fPromptSamples)
      {
        double prompt_sum = std::accumulate(SummedWaveforms[IndexToGrab].begin(), 
          SummedWaveforms[IndexToGrab].begin()+fPromptSamples, 
          0);
        double total_sum = std::accumulate(SummedWaveforms[IndexToGrab].begin(), 
          SummedWaveforms[IndexToGrab].end(), 
          0);
        PromptFraction = prompt_sum/total_sum;
      }
      lflash.prompt_fraction = PromptFraction;
    }

    //OpFlash Position calculation
    for(const auto& lflash :  flash_v) {

      // Get Flash Barycenter
      double Ycenter, Zcenter, Ywidth, Zwidth;
      _flashgeo->GetFlashLocation(lflash.channel_pe, Ycenter, Zcenter, Ywidth, Zwidth);

      // Get flasht0
      double flasht0 = lflash.time;

      // Refine t0 calculation
      if(_use_t0tool)
        flasht0 = _flasht0calculator->GetFlashT0(lflash.time, GetAssociatedLiteHits(lflash, ophits));

      // Subtract readout ReadoutDelay
      flasht0 = flasht0 -  _readout_delay;

      // Estimate drift location of the interaction and
      // make t0 unbias (lght propagation time correction)
      if(_correct_light_propagation){
        
        double drift_distance = _driftestimator->GetDriftPosition( lflash.channel_pe );
        double propagation_time = _driftestimator->GetPropagationTime( drift_distance );
        flasht0 = flasht0-propagation_time * 1e-3;

        drift_distance = (lflash.tpc==0 ? -drift_distance : drift_distance);

        recob::OpFlash flash(flasht0, lflash.time_err, trigger_time + flasht0,
                           (trigger_time + flasht0) / 1600., lflash.channel_pe,
                           0, 0, lflash.prompt_fraction, // this are just default values
                           drift_distance, -1, Ycenter, Ywidth, Zcenter, Zwidth);
        opflashes->emplace_back(std::move(flash));

      }
      else{
        recob::OpFlash flash(flasht0, lflash.time_err, trigger_time + flasht0,
                           (trigger_time + flasht0) / 1600., lflash.channel_pe,
                           0, 0, lflash.prompt_fraction, // this are just default values
                           100., -1, Ycenter, Ywidth, Zcenter, Zwidth);
        opflashes->emplace_back(std::move(flash));
      }

      // Create OpHit association
      for(auto const& hitidx : lflash.asshit_idx) {
        const art::Ptr<recob::OpHit> hit_ptr(ophit_v.at(hitidx));
        util::CreateAssn(*this, e, *opflashes, hit_ptr, *flash2hit_assn_v);
      }
    }

    e.put(std::move(opflashes));
    e.put(std::move(flash2hit_assn_v));
  }

  ::lightana::LiteOpHitArray_t SBNDFlashFinder::GetAssociatedLiteHits(::lightana::LiteOpFlash_t lite_flash,
                                                                      ::lightana::LiteOpHitArray_t lite_hits_v)
  {

    ::lightana::LiteOpHitArray_t flash_hits_v;

    for(auto const& hitidx : lite_flash.asshit_idx) {
      flash_hits_v.emplace_back(std::move(lite_hits_v.at(hitidx)));
    }

    return flash_hits_v;
  }
  //Changes to the order of processing in the PMT decoder or PMT deconvolution could break this function
  void ConstructSummedWaveforms(std::vector<raw::OpDetWaveform> InputChannels, 
      std::vector<std::vector<double>>& SummedWaveforms, std::vector<double>& SummedWaveformStartTimes, int TPC)
  {
    //Opdet waveforms are arranged first by CAEN, then flash, then PMT
    int NPMT=120; //Total TPC with entries in the deco waveform array
    int NFlashTriggers=InputChannels.size()/NPMT; // really distinct readout windows
    int NPMTPerCAEN=15;
    int NCAEN=NPMT/NPMTPerCAEN;
    for(int iFlash=0; iFlash<NFlashTriggers; iFlash++)
    {
      std::vector<double> TempSummedWaveform( InputChannels[iFlash*NPMTPerCAEN].Waveform().size() );
      SummedWaveformStartTimes.push_back(InputChannels[iFlash*NPMTPerCAEN].TimeStamp() );
      for(int iCAEN=0; iCAEN<NCAEN; iCAEN++)
      {
        for(int iPMT=0; iPMT<NPMTPerCAEN; iPMT++)
        {
          if(TPC==0)
          {
            //Have to grab the correct PMTs for this TPC
            //Wiring has paired PMTs from opposite TPC
            if(iPMT%2 == 0 && iPMT<14) continue; //other tpc
            if(iPMT==14 && iCAEN%2==0) continue;
          }
          else if(TPC==1)
          {
            if(iPMT%2==1 && iPMT<14) continue;
            if(iPMT==14 && iCAEN%2==1) continue;
          }
          int IndexToGrab = iCAEN*NFlashTriggers + iFlash*NPMTPerCAEN + iPMT;
          raw::OpDetWaveform ThisChannel = InputChannels[IndexToGrab];
          //Collect the samples and add them into the summed waveform
          for(int iSample=0; iSample<int(TempSummedWaveform.size()); iSample++)
          {
            TempSummedWaveform[iSample] += ThisChannel.Waveform()[iSample];
          }
        }
      }
    //Add summed waveform for this flash window to the collection
    SummedWaveforms.push_back(TempSummedWaveform);
    }
  }

  DEFINE_ART_MODULE(SBNDFlashFinder)

}//end namespace
