name: Auto Assign to Project(s)

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues and pull requests with `SBN-2020A_00` label to project 4
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'SBN-2020A_00') ||
        contains(github.event.pull_request.labels.*.name, 'SBN-2020A_00')
      with:
        project: 'https://github.com/orgs/SBNSoftware/projects/4'
        column_name: 'To Do'
